-module(ktn_code).

-export([
         beam_to_erl/2
        ]).

%% @doc If the beam was not compiled with debug_info
%%      the code generated by this function will look really ugly
%% @end
-spec beam_to_erl(string(), string()) -> ok.
beam_to_erl(BeamPath, ErlPath) ->
    case beam_lib:chunks(BeamPath, [abstract_code]) of
        {ok, {_, [{abstract_code, {raw_abstract_v1,Forms}}]}} ->
            Src =
                erl_prettypr:format(erl_syntax:form_list(tl(Forms))),
            {ok, Fd} = file:open(ErlPath, [write]),
            io:fwrite(Fd, "~s~n", [Src]),
            file:close(Fd);
        Error ->
            Error
    end.
